README.md
examples/_tags

To run a sample GraphQL server also serving GraphiQL, do the following:
```bash
git checkout git@github.com/andreas/ocaml-graphql-server.git
cd ocaml-graphql-server
opam pin add graphql-server .
cd examples
ocamlbuild -use-ocamlfind server.native && ./server.native
```
Now open [http://localhost:8080](http://localhost:8080).

Build instructions for GraphiQL example

---

src/graphql.mli
src/graphql_parser.ml
src/graphql_parser.mli
test/data/introspection.sexp
test/data/kitchen_sink.sexp

- Parser now handles `null` values.
- `Parser.key_value` a tuple `(string, Parser.value)` rather than a record.
- Floats and ints are now parsed together as "number", instead of separately, which didn't work correctly.

Parser improvements

---

.merlin
_tags
pkg/META
src/graphql.ml
test/schema_test.ml

- `Graphql.execute` now returns `(Yojson.Basic.json, string) result` rather than `Yojson.Basic.json`.
- Introduce `rresult` for more elegant `result` computations.
- Refactor some of the internals for schema execution.

Refactor schema execution

---

examples/_tags
examples/server.ml
src/graphql.ml
src/graphql.mli
test/argument_test.ml
test/schema_test.ml
test/test.ml
test/test_common.ml
test/test_schema.ml

A field new field `args` has been added to the field GADT:
```ocaml
type _ field = Field : {
name    : string;
args    : ('out, 'args) Arg.arg_list; (* <-- this field is new! *)
typ     : ('ctx, 'out) typ;
resolve : 'ctx -> 'src -> 'args;
} -> ('ctx, 'src) field
```
where `('a, 'b) Arg.arg_list` is a heterogenous list of arguments. The type of `resolve` is tied to the arguments in the following manner:
- If args are empty then the type is `('out, 'out) Arg.arg_list` and the type of `resolve` is `'ctx -> 'src -> 'out` as expected.
- If args have the the type `('out, string option -> int -> 'out) Arg.arg_list` (representing two arguments of type `string option` and `int`), then the type of `resolve` becomes `'ctx -> 'src -> string option -> int -> 'out)`.
At compile time we thus ensure that …

Argument support

---

_tags
pkg/META

Fix dependencies as specified in `_tags` and `META`:
- `lwt` should only be required when building `graphql.lwt`.
- `async_kernel` should only be required when building `graphql.async`.
- Neither should be required for building `graphql`.
fixes #17

Fix build dependencies for lwt/async subpackages

---

README.md
examples/index.html
examples/server.ml
opam
src/graphql_intf.ml
src/graphql_parser.ml
src/graphql_parser.mli
src/graphql_schema.ml
test/argument_test.ml
test/data/introspection.sexp
test/data/kitchen_sink.sexp
test/echo_schema.ml
test/schema_test.ml
test/test.ml
test/test_common.ml
test/variable_test.ml

This PR adds support for variables in query execution. The signature of `Graphql.execute` has been changed to:
```ocaml
type variables = (string * Graphql_parser.const_value) list
val execute : 'ctx schema ->
'ctx ->
?variables:variables ->
Graphql_parser.document ->
(Yojson.Basic.json, Yojson.Basic.json) result io
```
`Yojson.Basic.json` is a subtype of `Graphql_parser.const_value`, so you can parse a JSON string and coerce it to the type `variables`:
```ocaml
let json_variables = Yojson.Basic.(from_string "{\"x\": 42}" |> Util.to_assoc) in
let variables = (json_variables :> (string * Graphql_parser.const_value) list) in
Graphql.Schema.execute schema ctx ~variables doc
```
GraphiQL screenshot:
Depends on https://github.com/inhabitedtype/angstrom/pull/62.
resolves #5

Variable support in query execution

---

README.md
src/graphql_intf.ml
src/graphql_schema.ml
test/test_schema.ml

This PR adds the ability to define a recursive object type: an object with a field that refers to the type itself. An example would be a tweet, which has many replies (also tweets).
To achieve this, the fields of an object is now a function that receives the type itself and must return a list of fields. The new type of `obj` is thus:
```ocaml
val obj : name:string ->
fields:(('ctx, 'src option) typ -> ('ctx, 'src) field list) -> (* <-- new *)
('ctx, 'src option) typ
```
Example:
```ocaml
type tweet = {
id : int;
replies : tweet list;
}
let tweet = Schema.(obj
~name:"tweet"
~fields:(fun tweet -> [ (* <-- new *)
field "id"
~typ:(non_null int)
~args:Arg.[]
~resolver:(fun ctx t -> t.id)
;
field "replies"
~typ:(non_null (list tweet))
~args:Arg.[]
~resolver:(fun ctx t -> t.replies)
])
)
``` …

Allow recursive object types

---

examples/server.ml
src/graphql_intf.ml
src/graphql_schema.ml
test/argument_test.ml
test/echo_schema.ml

Default arguments doesn't work correctly in `master` right now. In particular, the type of `arg` isn't correct:
```ocaml
val arg : ?default:'a -> string -> ('a, 'b) arg_typ -> ('a, 'b) arg
```
Here `'a` is the "unification variable", and not the type of the content (as describe [here](https://drup.github.io/2016/08/02/difflists/)).
Specifying a default value for an argument only really makes sense if the argument is nullable, so the default value type and the argument type is interdependent. As such, two functions are now provided to construct arguments (with and without a default value):
```ocaml
val arg  : string -> typ:('a, 'b -> 'a) arg_typ -> ('a, 'b -> 'a) arg
val arg' : string -> typ:('a, 'b option -> 'a) arg_typ -> default:'b -> ('a, 'b -> 'a) arg
```
Example:
```ocaml
let schema …
```

Proper default arguments

---

examples/server.ml
src/graphql_intf.ml
src/graphql_schema.ml
test/echo_schema.ml
test/test_schema.ml

This PR adds a `doc` field to all relevant types, which is used for the `description` property in introspection queries. It thus allows you to document your objects, scalars, enums, etc.
Because `doc` is optional, the `name`-label has gone away for many functions, e.g.
```ocaml
(* before this PR *)
let role = Schema.enum ~name:"role" ~values:[(User, "user"); (Admin, "admin")]
(* after this PR *)
let role = Schema.enum "role" ~values:[(User, "user"); (Admin, "admin")] ~doc:"The role of a user"
```
closes #32

Add doc field to all relevant types

---

src/graphql_intf.ml
src/graphql_schema.ml
test/async_test.ml
test/echo_schema.ml
test/lwt_test.ml
test/schema_test.ml
test/test_schema.ml

[GraphiQL demo of mutation support](https://ocaml-graphql.herokuapp.com/?query=mutation%20%7B%0A%20%20add_number(number%3A%2042)%0A%7D&operationName=undefined) ✨ 
This PR implements support for mutations. The type of `Graphql.schema` has been updated from
```ocaml
(* Previous type *)
val schema : fields:('ctx, unit) field list ->
'ctx schema
```
to
```ocaml
(* New type *)
val schema : ?mutation_name:string ->
?mutations:('ctx, unit) field list ->
?query_name:string ->
('ctx, unit) field list ->
'ctx schema
```
The optional argument `~mutations` will be exposed as fields on the mutation root of the schema. Top-level mutation fields are executed serially as [described in the spec](https://facebook.github.io/graphql/#sec-Executing-Operations).
```ocaml
let numbers = ref []
let schema = …
```

Mutation support

---

.travis.yml
opam
src/graphql.ml
src/graphql_lwt.ml
src/graphql_schema.ml
src/graphql_schema.mli
test/async_test.ml

Had to revert d73a7e5, since those changes inadvertently assumed package versions from `janestreet-bleeding` repo.

Configure Travis

---

opam
src/graphql_parser.ml
test/argument_test.ml
test/variable_test.ml

- Bumped `angstrom` to 0.4.0 to get `Angstrom.scan_state`.
- Ignored characters are handled more efficiently.
- The parser accepts more GraphQL strings, though it still doesn't check if they are valid UTF-8 or replace escaped characters or unicode characters.

Improve parser

---

graphql/src/graphql_schema.ml
graphql/test/schema_test.ml

Selection of named operations was previously too simple and not [according to spec](https://facebook.github.io/graphql/#sec-Execution). This PR improves the implementation and adds more tests.
resolves #46

Fix selection of named operations

---

CHANGES.md
README.md
examples/server.ml
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml
graphql/test/echo_schema.ml
graphql/test/test_schema.ml

Previous an enum value was simply of type `('a * string)`, which didn't allow for documentation or deprecation. This PR introduces a proper `'a enum_value` type with the following accompanying function:
```ocaml
val enum_value : ?doc:string ->
?deprecated:deprecated ->
string ->
value:'a ->
'a enum_value
```
This also means that `enum` now accepts a list of `enum_value`:
```ocaml
val enum : ?doc:string ->
string ->
values:'a enum_value list ->
('ctx, 'a option) typ
```
Example usage:
```ocaml
type role = User | Admin
let role = Schema.(enum "role"
~values:[
enum_value "USER" ~value:User;
enum_value "ADMIN" ~value:Admin;
]
)
```
⚠️ NB. This breaks backwards compatibility! ⚠️ 
resolves #51

Documentation and deprecation for enum values

---

examples/jbuild
examples/server.ml
graphql-lwt.opam
graphql-lwt/src/assets/index.html
graphql-lwt/src/graphql_lwt.ml
graphql-lwt/src/graphql_lwt.mli
graphql-lwt/src/jbuild

This PR adds the following function:
```ocaml
Graphql_lwt.Server.start : ?port:int ->
ctx:(unit -> 'ctx) ->
'ctx Schema.schema ->
unit Lwt.t
```
This provides an easy way to expose a GraphQL schema over HTTP. It will run a HTTP server on port 8080 by default, expose a GraphQL endpoint on `POST /graphql`, and GraphiQL on `GET /graphql`. The path is currently not customizable. Static assets are provided via `jsdelivr.com`.
Example:
```ocaml
open Graphql_lwt
let schema = Schema.(schema
(* ... *)
)
let () =
(* assuming context is unit... *)
let mk_context () = () in
Server.start ~ctx:mk_context schema
|> Lwt_main.run
```

Add Server.start to Graphql_lwt

---

graphql/src/graphql_parser.ml

According to GraphQL spec tab should be treated as whitespace. Without this fix there is a parse error if a tab is inserted in a query.

Parse tab as whitespace

---

graphql-async/test/async_test.ml
graphql-lwt.opam
graphql-lwt/src/graphql_lwt.ml
graphql-lwt/test/lwt_test.ml
graphql/test/argument_test.ml
graphql/test/introspection_test.ml
graphql/test/schema_test.ml
graphql/test/test_common.ml
graphql/test/variable_test.ml

This PR is just a bit of housekeeping. Rather than compare strings in the test assertions, use `Yojson.Basic.json` values instead.
Also includes an update to depend on `cohttp-lwt-unix` version 1.0.0.

Use yojson for test assertions

---

CHANGES.md
graphql_parser.opam
graphql_parser/src/graphql_parser.ml
graphql_parser/test/data/quoted_string.graphql
graphql_parser/test/data/quoted_string.sexp
graphql_parser/test/parser_test.ml

- Depend on `angstrom` 0.7.0: https://github.com/ocaml/opam-repository/pull/10286/#issuecomment-329967555
- Fix parsing of escaped characters
closes #68

Parser fixes

---

CHANGES.md
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml

Previously argument types, `Schema.Arg.arg_typ`, was not generalizable, i.e. they could not be used in multiple contexts. Example that didn't work prior to this PR:
```ocaml
let silly_int = Schema.Arg.scalar "SillyInt"
~coerce:(function
| `Int n -> Ok (n+1)
| _ -> Error "Invalid silly int"
)
let schema = Schema.(schema [
field "foo"
~typ:(non_null int)
~args:Arg.[arg "a" ~typ:(non_null silly_int)]
~resolve:(fun _ () a -> a)
;
field "bar"
~typ:(non_null string)
~args:Arg.[arg "a" ~typ:(non_null silly_int)]  (* <-- this would fail! *)
~resolve:(fun _ () a -> string_of_int a)
])
```
This was an artifact of the clumsy way `Schema.Arg.arg_typ` was defined. With this PR, the above example works. Thanks to @drup for the suggested simplification.

Make custom argument types generalizable

---

graphql/src/graphql_schema.ml
graphql/test/introspection_test.ml

This PR adds deduplication of argument types which was previously missing. This meant the introspection response could contain duplicate argument types (see new test case).

Deduplicate arg types in introspection result

---

graphql/src/graphql_schema.ml
graphql/test/schema_test.ml

This PR prevents fragment cycles as [described in the spec](http://facebook.github.io/graphql/October2016/#sec-Fragment-spreads-must-not-form-cycles).

Prevent fragment cycles

---

graphql/src/graphql_schema.ml
graphql/test/schema_test.ml

The fragment cycle check introduced in #78 was flawed: the visited-set was reused across fields in the same selection set, which is incorrect. With this PR, the visited-set is only reused when traversing deeper in the query.

Fix fragment cycle check

---

examples/server.ml
graphql-lwt/src/graphql_lwt.ml
graphql-lwt/src/graphql_lwt.mli

This PR changes the type of `Graphql_lwt.Server.start`:
```ocaml
(* Before this PR *)
val start : ?port:int -> ctx:(unit -> 'ctx) -> 'ctx Schema.schema -> unit Lwt.t
(* After this PR *)
val start : ?port:int -> ctx:(Cohttp.Request.t -> 'ctx) -> 'ctx Schema.schema -> unit Lwt.t
```
This allows library users to construct a context that depends on the incoming HTTP request, e.g. cookies, headers, etc. Related to `https://github.com/andreas/ocaml-graphql-server/issues/43#issuecomment-378058396`.

Pass HTTP request to ctx function in Graphql_lwt.Server.start

---

graphql-async/test/async_test.ml
graphql-lwt/test/lwt_test.ml
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml
graphql/test/argument_test.ml
graphql/test/error_test.ml
graphql/test/jbuild
graphql/test/test.ml
graphql/test/variable_test.ml

This PR changes the type of `Schema.io_field`, such that the `resolve`-function must return a `('a, string) result`:
```ocaml
(* before *)
val io_field : ?doc:string ->
?deprecated:deprecated ->
string ->
typ:('ctx, 'out) typ ->
args:('out io, 'args) Arg.arg_list ->
resolve:('ctx -> 'src -> 'args) ->
('ctx, 'src) field
(* after *)
val io_field : ?doc:string ->
?deprecated:deprecated ->
string ->
typ:('ctx, 'out) typ ->
args:(('out, string) result io, 'args) Arg.arg_list ->
resolve:('ctx -> 'src -> 'args) ->
('ctx, 'src) field
```
Errors returned from `resolve`-functions will be exposed in the `errors`-part of the response. Nullable fields that return `Error` will be `null`, while errors from non-nullable fields will bubble up as [described in the …

Error handling

---

graphql-lwt/src/graphql_lwt.ml

Graphql_lwt: Return errors as JSON object

---

graphql/src/graphql_schema.ml
graphql/test/schema_test.ml

Resolves #100 
Had to add the `subscriptionType` field to the `__Schema` type because the introspection query used contains it, but I kept the behavior it used to have (always returning `null` since it didn't exist).
That will create a very small merge conflict when merging #101

Error on unexisting field

---

examples/server.ml
graphql-async/src/graphql_async.ml
graphql-async/src/graphql_async.mli
graphql-async/test/async_test.ml
graphql-lwt/src/graphql_lwt.ml
graphql-lwt/src/graphql_lwt.mli
graphql-lwt/test/lwt_test.ml
graphql.opam
graphql/src/graphql.ml
graphql/src/graphql.mli
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml
graphql/src/graphql_schema.mli
graphql/src/jbuild
graphql/test/schema_test.ml
graphql/test/test_common.ml
graphql/test/test_schema.ml

This is a WIP PR for adding subscription support to OCaml-GraphQL-Server.
- Right now a `SubscriptionField` has a `subscribe : 'ctx -> 'src -> 'args` and a `resolve : 'ctx -> 'out -> 'out` function. According to the spec, `resolve` is meant to be a mapper from `'out -> 'out`, and we want to return an `Io_stream.t` from `subscribe`. If we make both functions support `'args` I don't see a way to make them return different types. Maybe this is fine and `resolve` doesn't need args, but it'd be nice to have?
- Right now OGS gets the "source stream" from the `subscribe` function but not doing anything with it. This is the area where I have the most questions
- The spec mentions that the "response stream" is basically a "mapper" over the source stream that executes the selection set of the …

Subscription support

---

graphql/src/graphql_schema.ml
graphql/test/argument_test.ml
graphql/test/variable_test.ml

I had a really hard time discovering the source of an error for a script that was making GraphQL queries to OneGraph. The error was "Invalid string", but I had multiple string arguments. 
With this change, the error I get back is ``Argument `pos` of type `String` expected on field `updateCard`, found 1.``
With that error, there is enough context for me to easily pinpoint the problem and fix it.
If you'd like an easy way to test, this change is live on OneGraph:
```
curl 'https://serve.onegraph.com/dynamic?app_id=0b33e830-7cde-4b90-ad7e-2a39c57c0e11'  \
--data-binary '{"query":"{ trello { card { name }}}"}'
> {"data":null,"errors":[{"message":"Argument `id` of type `String!` expected on field `card`, but not provided."}]}
```

Improve error messages for invalid arguments

---

graphql/src/graphql_schema.ml
graphql/test/argument_test.ml
graphql/test/error_test.ml
graphql/test/schema_test.ml
graphql/test/variable_test.ml

According to the `Response Format`[section](https://facebook.github.io/graphql/June2018/#sec-Response-Format) of the GraphQL Spec:
> When errors is present in the response, it may be helpful for it to
appear first when serialized to make it more clear when errors are
present in a response during debugging.
refs #119

Add the `errors` key first in the response JSON

---

.travis.yml
examples/server.ml
graphql-async/src/graphql_async.ml
graphql-cohttp.opam
graphql-cohttp/src/assets/index.html
graphql-cohttp/src/dune
graphql-cohttp/src/graphql_cohttp.ml
graphql-cohttp/src/graphql_cohttp.mli
graphql-cohttp/src/websocket.ml
graphql-cohttp/src/websocket.mli
graphql-cohttp/src/websocket_handler.ml
graphql-lwt/src/graphql_lwt.ml
graphql/src/graphql.ml
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml

This PR is the first stab at adding a websocket transport ([protocol documentation](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md)). It's based on the following:
- [`anmonteiro/ocaml-subscriptions-transport-ws`](https://github.com/anmonteiro/ocaml-subscriptions-transport-ws), from which I've taken the main protocol handling and edited somewhat.
- [`vbmithr/ocaml-websocket`](https://github.com/vbmithr/ocaml-websocket), which has been simplified and made Mirage-compatible based on the thoughts [in this issue](https://github.com/vbmithr/ocaml-websocket/issues/105) and the work on [response actions for Cohttp_lwt](https://github.com/mirage/ocaml-cohttp/pull/647).
Note that this PR requires pinning `cohttp` to `master` until a new release is out.
The code …

First stab at websockets

---

graphql_parser.opam
graphql_parser/src/ast.ml
graphql_parser/src/dune

`Str` is not available on MirageOS freestanding, so replacing with `Re`.
See https://github.com/mirage/irmin/issues/632

Replace str with re

---

graphql-cohttp/src/dune
graphql-cohttp/src/graphql_cohttp.ml

Found this while experimenting with `irmin-mirage`
`graphql-cohttp` will need an update prior to the Irmin 2.0 release. I will add a note about this in the release issue (mirage/irmin#658).

Remove Str from cohttp-graphql

---

graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml

Relates to #145. Similar to #147, except deprecation warnings are suppressed locally.

Local disabling of Yojson deprecation warnings

---

graphql-cohttp/src/graphql_cohttp.ml

#146 inadvertently introduced a bug due to the different handling of empty parts when splitting strings:
```ocaml
(* Old implementation *)
Str.(split (regexp "/") "/graphql"
- : ["graphql"] : string list
(* New implementation *)
Astring.String.cuts ~sep:"/" "/graphql"
- : [""; "graphql"]
Astring.String.cuts ~sep:"/" "/graphql/"
- : [""; "graphql"; ""]
```
By adding `~empty:false`, the old behavior can be restored:
```ocaml
Astring.String.cuts ~empty:false ~sep:"/" "/graphql"
- : ["graphql"]
Astring.String.cuts ~empty:false ~sep:"/" "/graphql/"
- : ["graphql"]
```
This is preferable over changing the pattern matching (#149) due to handling of the trailing slashes.

Fix routing in graphql-cohttp

---

README.md

I couldn't reopen #125, so I created a new PR, but please feel free to close if you think it's not necessary and too verbose.
This is the full list of dependencies I needed to install, from a clean `opam switch create 4.07.1`, to get the example to run.

Update instructions to run the example project

---

graphql/src/graphql_schema.ml
graphql/test/variable_test.ml

This diff fixes the bug where the following valid query was returning an error saying the variable `first` was missing:
```graphql
query example(
$first: String! = 1
) {
greeter(first:$first)
}
```

Use default variables in operations

---

graphql-cohttp.opam
graphql-cohttp/src/graphql_cohttp.ml
graphql-cohttp/test/dune
graphql-cohttp/test/request_test.ml
graphql-cohttp/test/test.ml

This PR updates the parameter handling (extracting the query, variables and operation name from the HTTP request and body) in an attempt to match [the description on graphql.org](https://graphql.org/learn/serving-over-http/) and [`express-graphql`](https://github.com/graphql/express-graphql).
In essence, the parameters are extracted from both the query string and the HTTP body, and the two are merged with the former taking precedence.
Further, GraphiQL is not served unless the request explicitly requests HTML to allow get requests.
Remaining tasks:

graphql-cohttp: Improve parameter handling

---

graphql_parser.opam

Travis is currently failing because of `fmt 0.8.7`. Related to https://github.com/dbuenzli/fmt/commit/7e2b942ceb99a9406063c7540d9d8b582e936b85

graphql_parser: add upper bound for fmt

---

graphql-async/test/async_test.ml
graphql-lwt/test/lwt_test.ml
graphql/src/graphql_schema.ml
graphql/test/introspection_test.ml
graphql/test/test_common.ml

This PR adds the field `__type(name: String!)` to the top-level query object.
Todo:
closes #161

__type field

---

graphql-async/src/graphql_async.ml
graphql-async/src/graphql_async.mli
graphql-lwt/src/graphql_lwt.ml
graphql-lwt/src/graphql_lwt.mli
graphql/src/graphql.ml
graphql/src/graphql.mli
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml
graphql/src/graphql_schema.mli
graphql/test/custom_error_test.ml
graphql/test/dune
graphql/test/test.ml

Adds support for building a schema with a custom error type.
This allows users of ocaml-graphql-server to add extra error information in the extensions field of the error response. 
OneGraph is using this in production to provide more context in the errors that we display to the user. For example, we provide hints if the user is not logged in (try https://www.onegraph.com/graphiql?shortenedId=41WMZX) and nicely format json errors from upstream APIs (try https://www.onegraph.com/graphiql?shortenedId=VJSMV7).
There is a test with an example schema module:
```
module Err = struct
type t = | String of string | Extension of string * string
let message_of_error t = match t with
| String s -> s
| Extension _ -> ""
let extensions_of_error t = match t with
| String _ -> []
| Extension (k, v) -> …
```

Custom errors

---

graphql_parser.opam
graphql_parser/src/ast.ml

This will be unnecessary if #140 is merged. But until then, the constraint on `fmt` is quite annoying and can be easily fixed by adding explicit type annotations.

Fix for fmt >= 0.8.7

---

graphql/src/graphql_schema.ml
graphql/test/schema_test.ml

Fixes #167.
Merges selection sets in `collect_fields`.
Uses a StringMap to facilitate the merging, then walks the list of fields to ensure we haven't changed the ordering.

Merge fields defined in fragments

---

examples/server.ml

This PR adds logging to `./examples/server.exe` and outputs a where the server URL:
```
listening on http://localhost:8080/graphql
```
Hoping this makes it more intuitive for onboarding newcomers.

Add logging to the example

---

graphql/src/graphql_schema.ml
graphql/test/introspection_test.ml
graphql/test/schema_test.ml

1. Instrospection on `__typename`
2. No error was returned if requesting a subscription field that didn't
exist

Fix 2 subscriptions bugs

---

.ocamlformat
dune-project
graphql/test/schema_test.ml
graphql_parser/test/parser_test.ml

This PR adds `ocamlformat`, using the `conventional` format.
It only brings the minimum changes necessary to format the project:
```sh
$ dune build @fmt --auto-promote
```
After that it is expected that @andreas would commit those changes as the main author. After that we would enforce the formatting rules on travisCI (as per [@anmonteiro's suggestion](https://github.com/andreas/ocaml-graphql-server/issues/173#issuecomment-536330693)) to ensure that any new code merged follows the formatting rules.

Add ocamlformat

---

graphql/src/graphql_schema.ml
graphql/test/variable_test.ml

As raised in #181, missing variables are currently handled incorrectly: the request should not be rejected with an error all together, rather the variable should be handled as null. This PR updates the variable handling logic, such that this is the case.
Note that the error message is not great when a missing variable is used for a required argument. This will be revisited later.
closes #181

Handle missing variables as null

---

examples/server.ml
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml
graphql/test/argument_test.ml
graphql/test/echo_schema.ml
graphql/test/introspection_test.ml
graphql/test/test_schema.ml

Per https://github.com/andreas/ocaml-graphql-server/issues/31#issuecomment-674311844, changes the type of the `~default` argument in `arg'` to `Graphql_parser.const_value` to make it possible to populate the `defaultValue` field in the introspection query.

Show defaultValue in introspection query

---

graphql_parser/src/block_string.ml
graphql_parser/src/lexer.mll
graphql_parser/test/parser_test.ml

Adds parsing support for GraphQL's block string syntax.
With this change, the message arg in the following query will be parsed as `"Hello,\n  World!\n\nYours,\n  GraphQL."`, per the [spec](https://spec.graphql.org/draft/#sec-String-Value.Block-Strings).
```graphql
mutation {
sendEmail(message: """
Hello,
World!
Yours,
GraphQL.
""")
}
```
Test cases are lifted from the [block string tests in graphql-js](https://github.com/graphql/graphql-js/blob/main/src/language/__tests__/blockString-test.js).

Support block strings in the parser

---

graphql/src/graphql_schema.ml
graphql/test/directives_test.ml

Quick patch for skip/include directives on fragment spreads. 
The directives weren't being applied to the fragment spread because it was looking at the directives that were defined on the fragment definition (where skip and include aren't allowed).
In the example below, it was looking at (the made-up) `fragmentDefDirective` instead of the `skip` directive.
```
query TestQuery {
test {
...TestFragment @skip(if: true)    
}
}
fragment TestFragment on Test @fragmentDefDirective {
id
}
```
Includes a test.

Fix skip/include directives on fragment spreads

---

README.md
dune-project
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml
graphql/test/abstract_test.ml
graphql/test/echo_schema.ml
graphql/test/error_test.ml
graphql/test/schema_test.ml
graphql/test/test_common.ml
graphql/test/test_schema.ml

fixes #134 by implementing the proposed `fix` approach.

Recursive fields: add `Arg.fix` and `Schema.fix`

---

graphql-async.opam
graphql-async/test/async_test.ml
graphql-async/test/dune
graphql-lwt.opam
graphql-lwt/test/dune
graphql-lwt/test/lwt_test.ml
graphql.opam
graphql/src/graphql_intf.ml
graphql/src/graphql_schema.ml
graphql/test/test_common.ml

This fixes compatibility for the upcoming Yojson 2 while still working with Yojson >= 1.6.

Use Yojson `t` types instead of deprecated `json`

---

graphql.opam

The code needs at least version 0.2.0 of `rresult` for `>>=` and it needs at least 0.3.0 for `rresult` to use the `result` compatibility package to define a `result` type that is compatible with the stdlib `result` type.
Discovered via the minimum-version checks of https://github.com/ocaml/opam-repository/pull/21475

Raise minimum `rresult` version

---

graphql-cohttp/src/graphql_cohttp.ml
graphql-cohttp/test/request_test.ml
graphql_parser/src/ast.ml

fix: issue where Fmt.prefix is deprecated, replaced with ( ++ ); 
fix: issue andreas/ocaml-graphql-server#196 where content-type containing an encoding would fail to process

Fixes content-type + encoding issue
